# Generated by Django 4.2.13 on 2024-09-08 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebBeatSeller', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='cover_image',
        ),
        migrations.RemoveField(
            model_name='feature',
            name='name',
        ),
    ]
